language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email:
    - krifollk@gmail.com
